{
 "title": "Diagnóstico | CPU, RAM e HD",
 "tags": [
  "CPU",
  "RAM ",
  "HD"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Tempo em Atividade (Uptime)",
   "type": "stat",
   "description": "Quantidade de tempo em que o sistema está ligado de forma ininterrupta.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Consumo de CPU, Memória RAM e HD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Uso atual de Memória RAM",
   "type": "gauge",
   "description": "Porcentagem de uso da Memória RAM.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Uso atual de Memória SWAP",
   "type": "gauge",
   "description": "Porcentagem de uso de Memória SWAP. \n\nAltos valores indicam que a Memória RAM está sendo sobrecarregada.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes )) * 100"
    }
   ]
  },
  {
   "title": "Uso atual de HD | /data/",
   "type": "gauge",
   "description": "Porcentagem de uso HD.\n\nO valor informado, corresponde à porcentagem de consumo da partição que está montada no diretório /data/.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Uso atual de CPU (Processador)",
   "type": "gauge",
   "description": "Porcentagem de uso de todos os núcleos do Processador juntos.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle'}[5m])))) * 100) / count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "Memória RAM - Total",
   "type": "stat",
   "description": "Quantidade total de Memória RAM.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Memória SWAP - Total ",
   "type": "stat",
   "description": "Quantidade total de SWAP. \n\nValores acima de 30% indicam que o sistema está em mau funcionamento do sistema.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes" }
   ]
  },
  {
   "title": "HD (Disco Rígido) - Total ",
   "type": "stat",
   "description": "Espaço total para a persistência de Dados de infração/detecção.\n\nO valor informado, corresponde à porcentagem de consumo da partição que está montada no diretório /var/. Neste é salvo as detecções/infrações do sistema.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Núcleos da CPU (Processador)",
   "type": "stat",
   "description": "Número total de núcleos (cores) do processador do Não Legalmente Relevante.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  }
 ]
}